# -*- coding: utf-8 -*-
"""
webui/scripts.py — GUI 的数据核心：把每个入口脚本的命令行参数、以及 .env 配置项
结构化成 schema，前端据此自动生成表单。新增脚本/配置项只改这里。

参数类型(type)对应前端控件：
  bool   -> 勾选框(store_true，勾上才追加 --flag)
  int    -> 数字输入
  str    -> 文本输入
  choice -> 下拉(配 choices)
  multi  -> 多选(nargs="+"，选中的值空格分隔追加在 --flag 后)
positional=True 表示位置参数(不带 --，直接拼值)。
"""

# Complete ISO 3166-1 alpha-2 list. The registration worker still verifies the
# actual Cloudflare exit country before creating a browser profile.
CHATGPT_COUNTRY_CHOICES = ["auto", *"""
AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ
BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ
CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ
DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR
GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY
HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP
KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY
MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ
NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR
PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN
SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ
UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW
""".split()]
CHATGPT_COUNTRY_LABELS = {"auto": "自动"}

# ============================================================ 入口脚本 schema
SCRIPTS = [
    # ---------------------------------------------------------------- 主流程
    {
        "id": "run_full_flow",
        "file": "run_full_flow.py",
        "category": "主流程",
        "title": "端到端全流程",
        "desc": "并发注册 Outlook 邮箱，并为每个邮箱只运行一个所选平台。",
        "warning": "浏览器流程统一使用所选 Chromium provider；推荐 BitBrowser 以获得独立 Profile、Cookie 和指纹。",
        "args": [
            {"flag": "--platforms", "type": "choice", "choices": ["claude", "chatgpt", "grok", "kiro", "github"],
             "default": "claude", "help": "每个新邮箱只注册一个平台"},
            {"flag": "--rounds", "type": "int", "default": 1, "help": "循环注册轮数(0=无限循环)"},
            {"flag": "--concurrency", "type": "int", "default": 1, "help": "同时处理的端到端邮箱数；住宅代理池不足时自动降低"},
            {"flag": "--sequential-platforms", "type": "bool", "default": False,
             "help": "兼容旧参数；每个邮箱只注册一个平台"},
            {"flag": "--platform-retries", "type": "int", "default": 0,
             "help": "单个平台失败后的额外重试次数"},
            {"flag": "--platform-timeout", "type": "int", "default": 600, "help": "平台注册单号超时(秒)"},
            {"flag": "--round-sleep", "type": "int", "default": 5, "help": "每轮之间的等待秒数"},
            {"flag": "--skip-email", "type": "bool", "default": False, "help": "跳过邮箱注册，直接用下面指定的邮箱"},
            {"flag": "--email", "type": "str", "default": "", "help": "配合 --skip-email：现成邮箱"},
            {"flag": "--password", "type": "str", "default": "", "help": "配合 --email 的密码"},
            {"flag": "--email-attempts", "type": "int", "default": 30, "help": "邮箱注册最多尝试次数"},
            {"flag": "--email-timeout", "type": "int", "default": 180, "help": "单次邮箱注册硬超时(秒)"},
            {"flag": "--email-total-timeout", "type": "int", "default": 1800, "help": "邮箱阶段总超时(秒)"},
            {"flag": "--max-press", "type": "int", "default": 3, "help": "邮箱人机验证按住次数上限"},
            {"flag": "--email-confirm-before-register", "type": "bool", "default": False,
             "help": "邮箱注册页打开后自动点确认，再开始填写"},
            {"flag": "--node", "type": "str", "default": "auto", "help": "Claude/ChatGPT/Grok 使用的 Clash 节点"},
            {"flag": "--chatgpt-country", "type": "choice",
             "choices": CHATGPT_COUNTRY_CHOICES, "labels": CHATGPT_COUNTRY_LABELS,
             "countryNames": True,
             "default": "auto", "help": "仅约束 ChatGPT 的出口国家，并与网络节点关联"},
            {"flag": "--broker", "type": "str", "default": "", "help": "共享取码服务 URL；留空由各平台直接读取 Outlook"},
            {"flag": "--grok-timeout", "type": "int", "default": 40, "help": "Grok 共享邮箱取码超时(秒)"},
            {"flag": "--keep-on-fail", "type": "bool", "default": False, "help": "平台注册失败时保留浏览器窗口"},
            {"flag": "--codex", "type": "bool", "default": False, "help": "chatgpt 注册后走 Codex OAuth 导入 SUB2API(会接码过手机)"},
            {"flag": "--codex-sms-provider", "type": "choice", "choices": ["auto", "custom", "hero", "smsman", "firefox"],
             "labels": {"auto": "自动切换", "custom": "自定义号码池", "hero": "Hero SMS", "smsman": "SMS-Man", "firefox": "firefox.fun"},
             "default": "auto", "help": "Codex 接码平台；选择自定义会使用接码管理中批量导入的号码"},
            {"flag": "--custom-sms-pool-file", "type": "str", "default": "",
             "help": "自定义号码池 JSON 路径；留空使用接码管理中批量导入的默认池"},
            {"flag": "--custom-sms-allowed-hosts", "type": "str", "default": "",
             "help": "自定义接码记录域名白名单；允许这些 host 使用非公网 DNS，逗号分隔，留空保持严格校验"},
            {"flag": "--codex-phone-skip", "type": "int", "default": 0, "help": "正式接码前尝试免手机授权的次数"},
            {"flag": "--codex-phone-attempts", "type": "int", "default": 2, "help": "Codex add-phone 最大换号次数"},
            {"flag": "--codex-sms-timeout", "type": "int", "default": 150, "help": "单个手机号等待验证码秒数"},
            {"flag": "--sms-get-phone-retries", "type": "int", "default": 4, "help": "接码平台无库存时的取号重试次数"},
            {"flag": "--codex-timeout", "type": "int", "default": 120, "help": "Codex OAuth 授权捕获超时(秒)"},
            {"flag": "--codex-manual-phone", "type": "bool", "default": False, "help": "Codex add-phone 手动模式(自己在浏览器填号收码)"},
            {"flag": "--codex-phone", "type": "str", "default": "", "help": "自定义手机号(E.164)：自动填写并等待手动输入验证码"},
            {"flag": "--codex-group", "type": "str", "default": "", "help": "SUB2API 目标分组名(默认取配置)"},
            {"flag": "--grok-sub2api", "type": "bool", "default": False, "help": "grok 注册后把 SSO 转成 SUB2API Grok OAuth 账号"},
            {"flag": "--grok-sub2api-group", "type": "str", "default": "", "help": "SUB2API Grok 分组名(默认取配置)"},
            {"flag": "--grok-mailbox-attempts", "type": "int", "default": 6, "help": "Grok 发码失败时的邮箱尝试次数"},
            {"flag": "--claude-profile-retries", "type": "int", "default": 3, "help": "Claude 住宅出口被拒时的新 Profile 总尝试次数"},
            {"flag": "--claude-hcaptcha-retries", "type": "int", "default": 2, "help": "Claude hCaptcha 自动求解尝试次数"},
            {"flag": "--claude-challenge-wait", "type": "int", "default": 45, "help": "Claude 每个节点等待 Cloudflare 自动通过秒数"},
            {"flag": "--claude-challenge-node-retries", "type": "int", "default": 3, "help": "Claude 提交邮箱前的节点轮换次数"},
            {"flag": "--claude-captcha-manual-timeout", "type": "int", "default": 0, "help": "Claude 等待人工验证秒数；0 表示关闭"},
            {"flag": "--skip-claude-validation", "type": "bool", "default": False, "help": "跳过 Claude 对历史 sessionKey 的全量收尾校验"},
            {"flag": "--kiro-account-password", "type": "str", "default": "", "help": "Kiro Builder ID 密码；留空自动生成"},
            {"flag": "--kiro-full-name", "type": "str", "default": "Test User", "help": "Kiro Builder ID 显示名称"},
            {"flag": "--import-c2a", "type": "bool", "default": False, "help": "chatgpt 注册后即时导入 chatgpt2api(需配 CHATGPT2API_*)"},
            {"flag": "--plus-subscription", "type": "bool", "default": False, "help": "ChatGPT 注册成功后加入本地 Plus 订阅工作台"},
            {"flag": "--proxy", "type": "str", "default": "", "help": "覆盖 HTTP(S) 代理；留空使用配置中心的网络出口"},
            {"flag": "--clash-api", "type": "str", "default": "", "help": "覆盖 Clash Controller 地址；留空使用配置中心"},
            {"flag": "--clash-secret", "type": "str", "default": "", "help": "覆盖 Clash Controller 密码；留空使用配置中心"},
            {"flag": "--clash-group", "type": "str", "default": "", "help": "覆盖 Clash 策略组；留空使用配置中心"},
            {"flag": "--dry-run", "type": "bool", "default": False, "help": "只打印将执行的命令，不真注册(安全预览)"},
        ],
    },
    {
        "id": "register_three_platforms",
        "file": "register_three_platforms.py",
        "category": "主流程",
        "title": "平台注册(已有邮箱)",
        "desc": "用现成邮箱(或从 emails.txt 池)只在一个所选平台注册。",
        "args": [
            {"flag": "--from-pool", "type": "bool", "default": False, "help": "从 emails.txt 池取一个邮箱"},
            {"flag": "--email", "type": "str", "default": "", "help": "指定邮箱(不从池取时)"},
            {"flag": "--password", "type": "str", "default": "", "help": "邮箱密码"},
            {"flag": "--token", "type": "str", "default": "", "help": "Outlook refresh_token(走 Graph 取码)"},
            {"flag": "--client-id", "type": "str", "default": "", "help": "Outlook OAuth client_id"},
            {"flag": "--platforms", "type": "choice", "choices": ["claude", "chatgpt", "grok", "kiro", "github"],
             "default": "claude", "help": "每个邮箱只注册一个平台"},
            {"flag": "--parallel", "type": "bool", "default": False, "help": "兼容旧参数；单邮箱仅运行一个平台"},
            {"flag": "--loop", "type": "bool", "default": False, "help": "持续从池取号循环注册(常驻)"},
            {"flag": "--max-inflight", "type": "int", "default": 1, "help": "循环模式同时处理的邮箱数"},
            {"flag": "--codex", "type": "bool", "default": False, "help": "chatgpt 后走 Codex OAuth"},
            {"flag": "--grok-sub2api", "type": "bool", "default": False, "help": "grok 后导入 SUB2API Grok 渠道"},
            {"flag": "--grok-sub2api-group", "type": "str", "default": "", "help": "SUB2API Grok 分组名(默认取配置)"},
            {"flag": "--import-c2a", "type": "bool", "default": False, "help": "chatgpt 后导入 chatgpt2api"},
            {"flag": "--node", "type": "str", "default": "auto", "help": "Claude/ChatGPT/Grok Clash 节点"},
            {"flag": "--chatgpt-country", "type": "choice",
             "choices": CHATGPT_COUNTRY_CHOICES, "labels": CHATGPT_COUNTRY_LABELS,
             "countryNames": True,
             "default": "auto", "help": "仅约束 ChatGPT 的出口国家，并与网络节点关联"},
            {"flag": "--timeout", "type": "int", "default": 600, "help": "单平台超时(秒)"},
            {"flag": "--platform-retries", "type": "int", "default": 0, "help": "单个平台失败后的额外重试次数"},
            {"flag": "--keep-on-fail", "type": "bool", "default": False, "help": "失败时保留浏览器窗口"},
            {"flag": "--broker", "type": "str", "default": "http://127.0.0.1:8765", "help": "共享取码服务 URL；留空禁用"},
            {"flag": "--grok-timeout", "type": "int", "default": 40, "help": "Grok 共享邮箱取码超时(秒)"},
            {"flag": "--codex-group", "type": "str", "default": "", "help": "SUB2API 目标分组名(默认取配置)"},
            {"flag": "--codex-manual-phone", "type": "bool", "default": False, "help": "Codex add-phone 手动模式"},
            {"flag": "--codex-sms-provider", "type": "choice", "choices": ["auto", "custom", "hero", "smsman", "firefox"],
             "labels": {"auto": "自动切换", "custom": "自定义号码池", "hero": "Hero SMS", "smsman": "SMS-Man", "firefox": "firefox.fun"},
             "default": "auto", "help": "Codex 接码平台；自定义号码来自批量导入池"},
            {"flag": "--custom-sms-pool-file", "type": "str", "default": "", "help": "留空使用接码管理中批量导入的默认池"},
            {"flag": "--custom-sms-allowed-hosts", "type": "str", "default": "", "help": "接码记录域名白名单；允许这些 host 使用非公网 DNS，留空保持严格校验"},
            {"flag": "--codex-phone-skip", "type": "int", "default": 0, "help": "接码前尝试免手机授权的次数"},
            {"flag": "--codex-phone-attempts", "type": "int", "default": 2, "help": "Codex add-phone 最大换号次数"},
            {"flag": "--codex-sms-timeout", "type": "int", "default": 150, "help": "单个手机号等待验证码秒数"},
            {"flag": "--sms-get-phone-retries", "type": "int", "default": 4, "help": "接码平台无库存时的取号重试次数"},
            {"flag": "--codex-timeout", "type": "int", "default": 120, "help": "Codex OAuth 授权捕获超时(秒)"},
            {"flag": "--plus-subscription", "type": "bool", "default": False, "help": "ChatGPT 注册成功后加入本地 Plus 订阅工作台"},
            {"flag": "--grok-mailbox-attempts", "type": "int", "default": 6, "help": "Grok 发码失败时的邮箱尝试次数"},
            {"flag": "--claude-profile-retries", "type": "int", "default": 3, "help": "Claude 住宅出口被拒时的新 Profile 总尝试次数"},
            {"flag": "--claude-hcaptcha-retries", "type": "int", "default": 2, "help": "Claude hCaptcha 自动求解尝试次数"},
            {"flag": "--claude-challenge-wait", "type": "int", "default": 45, "help": "Claude 每节点等待 Cloudflare 自动通过秒数"},
            {"flag": "--claude-challenge-node-retries", "type": "int", "default": 3, "help": "Claude 提交邮箱前的节点轮换次数"},
            {"flag": "--claude-captcha-manual-timeout", "type": "int", "default": 0, "help": "Claude 等待人工验证秒数；0 表示关闭"},
            {"flag": "--no-claude-auto-validate", "type": "bool", "default": False, "help": "跳过 Claude 对历史 sessionKey 的全量收尾校验"},
            {"flag": "--kiro-account-password", "type": "str", "default": "", "help": "Kiro Builder ID 密码；留空自动生成"},
            {"flag": "--kiro-full-name", "type": "str", "default": "Test User", "help": "Kiro Builder ID 显示名称"},
            {"flag": "--poll-wait", "type": "int", "default": 20, "help": "循环模式邮箱池为空时的轮询秒数"},
        ],
    },
    {
        "id": "oauth_codex",
        "file": "oauth_codex.py",
        "platform": "chatgpt",
        "category": "主流程",
        "title": "Codex OAuth 授权 → SUB2API",
        "desc": "用已存 cookie 重登 ChatGPT，走 OAuth 拿带 refresh_token 的凭据建到 SUB2API/CPA。默认直接接码过 add-phone。",
        "args": [
            {"flag": "--cookie", "type": "str", "default": "", "help": "cookie 文件路径(默认最新 full_*.json)"},
            {"flag": "--phone-skip", "type": "int", "default": 0, "help": "先赌免手机直连次数(0=直接接码不赌)"},
            {"flag": "--sms-provider", "type": "choice", "choices": ["auto", "custom", "hero", "smsman", "firefox"],
             "labels": {"auto": "自动切换", "custom": "自定义号码池", "hero": "Hero SMS", "smsman": "SMS-Man", "firefox": "firefox.fun"},
             "default": "auto", "help": "add-phone 使用的接码平台；可强制指定 Hero SMS"},
            {"flag": "--node", "type": "str", "default": "auto", "help": "固定 Clash 出口；auto 自动探测"},
            {"flag": "--manual-phone", "type": "bool", "default": False, "help": "手动模式：自己在浏览器填号+输码"},
            {"flag": "--phone", "type": "str", "default": "", "help": "半自动：脚本填该号(E.164)+选WhatsApp，你只手输码"},
            {"flag": "--group", "type": "str", "default": "", "help": "SUB2API 目标分组(默认取配置)"},
            {"flag": "--skip-cpa", "type": "bool", "default": False, "help": "不推 CPA(默认配好就推)"},
            {"flag": "--keep", "type": "bool", "default": False, "help": "失败保留窗口便于排查"},
        ],
    },
    {
        "id": "plus_codex_import",
        "file": "tools/import_plus_codex.py",
        "platform": "chatgpt",
        "category": "主流程",
        "title": "已开通 Plus 批量导入 SUB2API",
        "desc": "兼容 Outlook/iCloud 邮箱、ChatGPT session token 和完整 OAuth JSON；手机号验证通过后导入 SUB2API。",
        "args": [
            {"flag": "--accounts-file", "type": "str", "default": "", "help": "邮箱、Cookie 或 token 批量文件路径"},
            {"flag": "--group", "type": "str", "default": "codex", "help": "SUB2API OpenAI 分组"},
            {"flag": "--concurrency", "type": "int", "default": 1, "help": "并发账号数（1-5）"},
            {"flag": "--node", "type": "str", "default": "auto", "help": "ChatGPT Clash 节点"},
            {"flag": "--sms-provider", "type": "choice", "choices": ["auto", "custom", "smsman", "firefox", "hero"],
             "labels": {"auto": "自动切换", "custom": "自定义号码池", "smsman": "SMS-Man", "firefox": "firefox.fun", "hero": "Hero SMS"},
             "default": "auto", "help": "手机号接码平台"},
            {"flag": "--phone-attempts", "type": "int", "default": 3, "help": "单账号最多换号次数"},
            {"flag": "--sms-timeout", "type": "int", "default": 180, "help": "单号等码秒数"},
            {"flag": "--timeout", "type": "int", "default": 600, "help": "单账号 OAuth 超时秒数"},
            {"flag": "--skip-phone", "type": "bool", "default": False, "help": "跳过手机号/2FA 验证，仅保存或导出凭据"},
            {"flag": "--no-import", "type": "bool", "default": False, "help": "不创建 SUB2API 账号"},
            {"flag": "--output-format", "type": "choice", "choices": ["none", "sub2api"],
             "labels": {"none": "不额外输出", "sub2api": "SUB2API token JSON"},
             "default": "none", "help": "成功凭据的额外输出格式"},
            {"flag": "--output", "type": "str", "default": "", "help": "额外 token 输出文件"},
            {"flag": "--keep-on-fail", "type": "bool", "default": False, "help": "失败时保留浏览器窗口"},
            {"flag": "--delete-input", "type": "bool", "default": False, "help": "读取后删除账号文件"},
            {"flag": "--dry-run", "type": "bool", "default": False, "help": "只验证账号格式"},
        ],
    },
    # ---------------------------------------------------------------- 单平台注册
    {
        "id": "register_chatgpt",
        "file": "register_chatgpt.py",
        "platform": "chatgpt",
        "category": "单平台注册",
        "title": "ChatGPT 注册",
        "desc": "ChatGPT 单平台注册，支持 iCloud 接码，并可在成功后直接导入 SUB2API。",
        "args": [
            {"flag": "--count", "type": "int", "default": 1, "help": "注册数量"},
            {"flag": "--timeout", "type": "int", "default": 480, "help": "单号超时(秒)"},
            {"flag": "--node", "type": "str", "default": "auto",
             "help": "固定 Clash 出口；auto 自动探测，none 直连"},
            {"flag": "--country", "type": "choice",
             "choices": CHATGPT_COUNTRY_CHOICES, "labels": CHATGPT_COUNTRY_LABELS,
             "countryNames": True,
             "default": "auto", "help": "按出口国家筛选网络并校验 Cloudflare loc；找不到匹配出口则停止"},
            {"flag": "--email-provider", "type": "choice", "choices": ["", "pool", "icloud", "remail"],
             "labels": {"": "按 .env 配置", "pool": "Outlook 邮箱池", "icloud": "iCloud API 接码", "remail": "Remail 邮箱"},
             "default": "", "help": "邮箱来源；留空使用 CHATGPT_EMAIL_PROVIDER 配置"},
            {"flag": "--codex", "type": "bool", "default": False,
             "help": "注册成功后直接导入 SUB2API；需配置 SUB2API_*，OAuth 期间可能需要手机验证"},
            {"flag": "--enable-2fa", "type": "bool", "default": True,
             "help": "注册完成后启用验证器 TOTP，并把密钥写入账号资产"},
            {"flag": "--import-c2a", "type": "bool", "default": False, "help": "注册后导入 chatgpt2api"},
            {"flag": "--concurrency", "type": "int", "default": 1,
             "help": "并发数；住宅代理池隔离出口；指定固定 Clash 节点也可共享 IP 并发"},
            {"flag": "--email", "type": "str", "default": "", "help": "指定邮箱(绕过池)"},
            {"flag": "--password", "type": "str", "default": "", "help": "邮箱密码"},
            {"flag": "--refresh-token", "type": "str", "default": "", "help": "Outlook refresh_token"},
            {"flag": "--client-id", "type": "str", "default": "", "help": "Outlook OAuth client_id"},
            {"flag": "--codex-group", "type": "str", "default": "", "help": "SUB2API 目标分组名；留空使用配置值"},
            {"flag": "--codex-sms-provider", "type": "choice", "choices": ["auto", "custom", "hero", "smsman", "firefox"],
             "labels": {"auto": "自动切换", "custom": "自定义号码池", "hero": "Hero SMS", "smsman": "SMS-Man", "firefox": "firefox.fun"},
             "default": "auto", "help": "直接导入 SUB2API 时的手机接码平台"},
            {"flag": "--codex-manual-phone", "type": "bool", "default": False, "help": "Codex 手动填号收码"},
            {"flag": "--codex-phone", "type": "str", "default": "", "help": "自定义手机号(E.164)：自动填写并等待手动输入验证码"},
            {"flag": "--keep-on-fail", "type": "bool", "default": False, "help": "失败保留窗口"},
        ],
    },
    {
        "id": "register_grok",
        "file": "register_grok.py",
        "platform": "grok",
        "category": "单平台注册",
        "title": "Grok 注册",
        "desc": "使用指纹浏览器注册 Grok，支持 Outlook 或配置的临时邮箱，成功后可导入 SUB2API。",
        "warning": "Grok 使用 Chromium CDP；推荐 BitBrowser 或内置 Chromium。",
        "args": [
            {"flag": "--count", "type": "int", "default": 1, "help": "注册数量"},
            {"flag": "--concurrency", "type": "int", "default": 1,
             "help": "并发数；住宅代理池可隔离出口，固定 Clash 节点可共享 IP 并发"},
            {"flag": "--timeout", "type": "int", "default": 600, "help": "单号超时(秒)"},
            {"flag": "--node", "type": "str", "default": "auto",
             "help": "Clash 模式下的出口节点；auto 自动探测，住宅模式下忽略"},
            {"flag": "--latest-rt", "type": "bool", "default": False,
             "help": "使用 emails.txt 中最新未占用且带 RT/client_id 的 Outlook，Graph API 取码"},
            {"flag": "--sub2api", "type": "bool", "default": False,
             "help": "注册成功后直接导入 SUB2API Grok 渠道"},
            {"flag": "--sub2api-group", "type": "str", "default": "",
             "help": "目标 Grok 分组名，留空使用 SUB2API_GROK_GROUP"},
            {"flag": "--mailbox-attempts", "type": "int", "default": 6,
             "help": "发码未进入验证码页时自动更换临时邮箱的次数"},
            {"flag": "--keep-on-fail", "type": "bool", "default": False,
             "help": "失败时保留测试窗口"},
        ],
    },
    {
        "id": "register_claude",
        "file": "register.py",
        "platform": "claude",
        "category": "单平台注册",
        "title": "Claude 注册",
        "desc": "Claude 单平台注册；支持 YYDS 临时邮箱，自动处理节点预检、magic-link 原生验证和 hCaptcha，成功后保存 sessionKey。",
        "warning": "运行前必须在“配置 (.env) → Claude 注册与验证”中填写视觉 API 地址和 key。Claude 使用 Chromium CDP。",
        "args": [
            {"flag": "--count", "type": "int", "default": 1, "help": "注册数量"},
            {"flag": "--concurrency", "type": "int", "default": 1,
             "help": "并发数；每个任务独立 Profile；固定 Clash 节点可共享 IP 并发"},
            {"flag": "--timeout", "type": "int", "default": 480, "help": "单号超时(秒)"},
            {"flag": "--provider", "type": "choice",
             "choices": ["", "yyds", "gptmail", "cfmail", "moemail", "custom"], "default": "",
             "labels": {"": "Outlook 资产池", "yyds": "YYDS 临时邮箱", "gptmail": "GPTMail 临时邮箱", "cfmail": "CFMail 临时邮箱", "moemail": "MoeMail 临时邮箱", "custom": "自定义临时邮箱"},
             "help": "邮箱来源；选择临时邮箱后忽略 Outlook/最新 RT"},
            {"flag": "--domain", "type": "str", "default": "",
             "help": "临时邮箱域名；留空由 provider 自动选择"},
            {"flag": "--latest-rt", "type": "bool", "default": True,
             "help": "Outlook 模式默认使用 emails.txt 中最新未占用且可读 Graph 的 RT 邮箱"},
            {"flag": "--mailbox-attempts", "type": "int", "default": 3,
             "help": "Claude 邮件未进入收件箱或垃圾箱时，自动更换健康 Outlook 的次数"},
            {"flag": "--node", "type": "str", "default": "auto", "help": "Clash 模式下自动轮换；住宅模式下忽略"},
            {"flag": "--email", "type": "str", "default": "", "help": "指定邮箱(调试)"},
            {"flag": "--password", "type": "str", "default": "", "help": "邮箱密码"},
            {"flag": "--token", "type": "str", "default": "", "help": "refresh token"},
            {"flag": "--client-id", "type": "str", "default": "", "help": "与 refresh token 配套的 Outlook OAuth client_id"},
            {"flag": "--challenge-wait", "type": "int", "default": 45,
             "help": "每个节点等待 Cloudflare 自动验证的秒数"},
            {"flag": "--challenge-node-retries", "type": "int", "default": 3,
             "help": "提交邮箱前最多轮换节点次数"},
            {"flag": "--captcha-manual-timeout", "type": "int", "default": 0,
             "help": "等待手动图形验证秒数(0=关闭)"},
        ],
    },
    {
        "id": "register_kiro",
        "file": "register_kiro.py",
        "platform": "kiro",
        "category": "单平台注册",
        "title": "Kiro 注册",
        "desc": "使用 Outlook、自建邮箱 API 或临时邮箱注册 AWS Builder ID，并导出 Kiro 所需的长期凭据。",
        "args": [
            {"flag": "--count", "type": "int", "default": 1, "help": "注册数量"},
            {"flag": "--concurrency", "type": "int", "default": 1,
             "help": "并发数；每个任务使用独立 HTTP Session 和设备指纹"},
            {"flag": "--timeout", "type": "int", "default": 600, "help": "单号超时(秒)"},
            {"flag": "--email", "type": "str", "default": "", "help": "指定邮箱(留空从 Outlook 资产池取)"},
            {"flag": "--password", "type": "str", "default": "", "help": "Outlook 邮箱密码(与邮箱资产一并记录)"},
            {"flag": "--refresh-token", "type": "str", "default": "", "help": "Outlook Graph refresh token"},
            {"flag": "--client-id", "type": "str", "default": "", "help": "Outlook OAuth client_id"},
            {"flag": "--email-provider", "type": "choice", "choices": ["pool", "temp", "custom"],
             "default": "pool", "help": "邮箱来源：Outlook 资产池、TEMP_EMAIL_PROVIDER 或自建 CUSTOM_MAIL_* API"},
            {"flag": "--temp-provider", "type": "choice",
             "choices": ["", "yyds", "remail", "gptmail", "moemail", "cfmail", "icloud", "custom"],
             "labels": {"": "按 .env 配置", "yyds": "YYDS 临时邮箱", "remail": "Remail 临时邮箱",
                        "gptmail": "GPTMail 临时邮箱", "moemail": "MoeMail 临时邮箱",
                        "cfmail": "CFMail 临时邮箱", "icloud": "iCloud 临时邮箱", "custom": "自定义临时邮箱"},
             "default": "",
             "help": "临时邮箱 provider 覆盖值，如 remail、yyds、gptmail"},
            {"flag": "--account-password", "type": "str", "default": "", "help": "Kiro 账号密码(留空随机生成)"},
            {"flag": "--full-name", "type": "str", "default": "Test User", "help": "Builder ID 显示名称"},
        ],
    },
    {
        "id": "register_github",
        "file": "register_github.py",
        "platform": "github",
        "category": "单平台注册",
        "title": "GitHub 注册",
        "desc": "GitHub 注册(含 Arkose 验证视觉求解，需配 VISION_*/VOTE_*)。",
        "args": [
            {"flag": "--count", "type": "int", "default": 1, "help": "注册数量"},
            {"flag": "--concurrency", "type": "int", "default": 1,
             "help": "并发数；住宅代理池按槽隔离出口，出口不足时自动降低并发"},
            {"flag": "--auto", "type": "bool", "default": False, "help": "走完整流程(含取 launch code)"},
            {"flag": "--email", "type": "str", "default": "", "help": "指定邮箱(默认从 _outlook_pool 取)"},
            {"flag": "--password", "type": "str", "default": "", "help": "邮箱密码"},
            {"flag": "--no-keep", "type": "bool", "default": False, "help": "结束后删窗口(默认保留)"},
            {"flag": "--timeout", "type": "int", "default": 600, "help": "超时(秒)"},
        ],
    },
    # ---------------------------------------------------------------- 邮箱注册
    {
        "id": "outlook_reg_loop",
        "file": "outlook_reg_loop.py",
        "platform": "outlook",
        "category": "邮箱注册",
        "title": "Outlook 邮箱注册",
        "desc": "持续自注册 Outlook；最近窗口成功率低于阈值时自动停止，避免持续消耗住宅流量。",
        "warning": "Outlook 浏览器注册、Graph 授权和账号恢复均使用当前选择的 Chromium provider；推荐 BitBrowser。",
        "args": [
            {"flag": "--count", "type": "int", "default": 0,
             "help": "可选硬上限（0=不限制总次数）"},
            {"flag": "--concurrency", "type": "int", "default": 1,
             "help": "并发数；住宅代理池按槽隔离；固定 Clash 节点可共享 IP 并发"},
            {"flag": "--node", "type": "str", "default": "auto",
             "help": "无住宅代理时可指定一个 Clash 节点，以共享固定公网 IP 并发"},
            {"flag": "--target-pool", "type": "int", "default": 0, "help": "池达到此数量就停(0=不限)"},
            {"flag": "--min-success-rate", "type": "int", "default": 10,
             "help": "最近窗口最低成功率百分比（0=关闭成功率熔断）"},
            {"flag": "--success-rate-window", "type": "int", "default": 20,
             "help": "成功率统计窗口；完成这么多次后才开始判断"},
            {"flag": "--max-press", "type": "str", "default": "5", "help": "人机验证按住次数上限"},
            {"flag": "--confirm-before-register", "type": "bool", "default": False,
             "help": "注册页打开后仅在出现数据许可页时才点确认(正常表单不点)"},
            {"flag": "--timeout", "type": "int", "default": 180, "help": "单号注册超时(秒)"},
            {"flag": "--sleep", "type": "int", "default": 5, "help": "每次注册间隔(秒)"},
            {"flag": "--sleep-when-full", "type": "int", "default": 60, "help": "池达标时的休眠间隔(秒)"},
            {"flag": "--no-rotate", "type": "bool", "default": False,
             "help": "不轮换 Clash 节点，固定用当前节点(也可用 OUTLOOK_NO_ROTATE=1)"},
        ],
    },
    {
        "id": "unlock_outlook",
        "file": "unlock_outlook.py",
        "platform": "outlook",
        "category": "邮箱注册",
        "title": "解锁 Outlook + 提取 Graph",
        "desc": "一次处理待解锁、RT 过期或缺少 RT 的 Outlook；恢复登录后提取 Graph token 并回写邮箱池。",
        "args": [
            {"flag": "--input", "type": "str", "default": "", "help": "账号文件(每行 email----password；留空读取资产状态)"},
            {"flag": "--proxy-file", "type": "str", "default": "", "help": "住宅代理池文件"},
            {"flag": "--concurrency", "type": "int", "default": 1, "help": "并发数"},
            {"flag": "--statuses", "type": "multi",
             "choices": ["unlock", "expired", "unknown", "banned"],
             "default": ["unlock", "expired", "unknown"],
             "help": "自动模式处理的资产状态；unknown 仅包含缺少 RT 的邮箱，封禁账号需手动勾选"},
        ],
    },
    {
        "id": "mailbox_broker",
        "file": "mailbox_broker.py",
        "category": "邮箱注册",
        "title": "共享取码服务(常驻)",
        "desc": "并行流水线时起共享取码服务，避免三窗口并发登录同一邮箱。常驻运行。",
        "args": [
            {"flag": "--host", "type": "str", "default": "127.0.0.1", "help": "监听地址"},
            {"flag": "--port", "type": "int", "default": 8765, "help": "监听端口"},
            {"flag": "--idle", "type": "int", "default": 480, "help": "空闲会话回收秒数"},
        ],
    },
    # ---------------------------------------------------------------- 导出 / 上传
    {
        "id": "upload_tokens",
        "file": "tools/upload_tokens.py",
        "category": "导出/上传",
        "title": "上传标准 token",
        "desc": "把 tokens/ 下标准 token 上传到 CPA/SUB2API/webchat2api；Grok 会导入 SUB2API Grok 渠道。",
        "args": [
            {"flag": "target", "type": "choice", "choices": ["all", "chatgpt", "grok"],
             "default": "all", "positional": True, "help": "上传目标"},
        ],
    },
    {
        "id": "export_chatgpt2api",
        "file": "tools/export_chatgpt2api.py",
        "category": "导出/上传",
        "title": "导出/上传 chatgpt2api",
        "desc": "聚合普通网页号导入 chatgpt2api(--post 直传 / 默认导出 txt)。",
        "args": [
            {"flag": "--post", "type": "str", "default": "", "help": "直接 POST 到的 host(留空只导出文件)"},
            {"flag": "--key", "type": "str", "default": "", "help": "chatgpt2api admin key(配合 --post)"},
            {"flag": "--json", "type": "bool", "default": False, "help": "导出 JSON(默认一行一个 access_token)"},
            {"flag": "--out", "type": "str", "default": "", "help": "输出文件路径"},
        ],
    },
    {
        "id": "export_accounts",
        "file": "tools/export_accounts.py",
        "category": "导出/上传",
        "title": "导出平台 Cookie",
        "desc": "按平台和 index 导出标准浏览器 Cookie，或生成直登扩展账号包。",
        "args": [
            {"flag": "--platform", "type": "choice", "choices": ["all", "claude", "chatgpt", "grok"],
             "default": "all", "help": "cookies 格式必须指定一个平台"},
            {"flag": "--format", "type": "choice", "choices": ["accounts", "cookies"],
             "default": "accounts", "help": "cookies 为标准浏览器导入数组"},
            {"flag": "--index", "type": "int", "default": -1,
             "help": "-1=账号包全部/标准 Cookie 第一条；其他值精确指定账号"},
            {"flag": "--out", "type": "str", "default": "", "help": "可选输出 JSON 路径"},
        ],
    },
    {
        "id": "export_kiro_credentials",
        "file": "tools/export_kiro_credentials.py",
        "category": "导出/上传",
        "title": "导出 Kiro 凭证",
        "desc": "把已保存的 Kiro 账号聚合成 hank9999/kiro.rs 可直接读取的 credentials.json。",
        "args": [
            {"flag": "--output", "type": "str", "default": "", "help": "可选输出 JSON 路径"},
        ],
    },
]


def script_by_id(sid):
    for s in SCRIPTS:
        if s["id"] == sid:
            return s
    return None


# ============================================================ 外部工具链接
# 不在本机跑的 web 服务/工具，面板上以"打开链接"卡片呈现(新标签打开)。
EXTERNAL_LINKS = [
    {
        "id": "download_clash_verge",
        "title": "下载 Clash Verge 2.5.2",
        "url": "https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v2.5.2/Clash.Verge_2.5.2_x64-setup.exe",
        "desc": "Windows x64 安装包",
    },
    {
        "id": "download_bitbrowser",
        "title": "下载 BitBrowser",
        "url": "https://www.bitbrowser.cn/download",
        "desc": "BitBrowser 官方下载页",
    },
]


# ============================================================ 内嵌功能页
# 直接在面板里 iframe 内嵌的外部页面 + 可选 sms-man 接码助手。
# 空列表时前端不渲染「功能」导航区(app.js: if(EMBEDS.length))，内嵌视图/接码助手一并隐藏。
# Gmail 注册已下线；如需重新内嵌某页，按下面注释里的字段格式往列表里加即可。
#   {"id": "xxx", "title": "标题", "url": "https://...", "desc": "说明",
#    "sms_helper": True, "sms_service_default": "google"}
EMBED_PAGES = []


# ============================================================ .env 配置 schema
# group: 分组标题；key: 变量名；required: 是否必填(运行对应功能时)；help: 说明；
# secret: True 时前端用密码框；default: 模板默认值(仅展示)。
ENV_SCHEMA = [
    {"group": "Codex K12 控制台", "tests": [{"target": "k12", "label": "测试 K12 控制台"}], "items": [
        {"key": "K12_CONSOLE_URL", "default": "http://127.0.0.1:8806",
         "help": "主 WebUI 内嵌的 Codex K12 地址。本地地址会由主 WebUI 自动管理进程。"},
        {"key": "K12_AUTO_START", "type": "choice", "choices": ["1", "0"], "default": "1",
         "help": "启动主 WebUI 时是否自动拉起本地 Codex K12 服务。"},
    ]},
    {"group": "本地资产 API", "items": [
        {"key": "REG_FACTORY_ASSET_API_KEY", "secret": True,
         "help": "可选；配置后调用邮箱/Cookie 读取 API 必须提供 X-API-Key 或 Bearer Token。留空时仅允许本机访问。"},
        {"key": "ASSET_SCAN_CHATGPT_PLUS_TRIAL", "type": "bool", "default": "true",
         "help": "扫描正常 ChatGPT 账号时调用优惠资格接口，标注 Plus 免费试用资格；失败仅标为未知，不影响账号健康状态。"},
        {"key": "ASSET_SCAN_CHATGPT_PLUS_CAMPAIGN", "default": "plus-1-month-free",
         "help": "ChatGPT Plus 试用资格检测使用的活动标识。"},
    ]},
    {"group": "Plus 协议提链", "items": [
        {"key": "REG_FACTORY_PROTOCOL_PAYMENT_ROOT",
         "help": "可选；GPT-Register-Tool 本地目录。留空时自动查找同级目录，用于 Plus 导入后的批量协议提链。"},
    ]},
    {"group": "网络出口", "tests": [{"target": "clash", "label": "测试 Clash 连通"}], "items": [
        {"key": "PROXY_MODE", "type": "choice", "choices": ["clash_auto", "clash_fixed", "residential"],
         "default": "clash_auto", "help": "Clash 自动轮换、固定节点，或动态住宅代理。建议在左侧“网络出口”页配置。"},
        {"key": "OUTLOOK_PROXY_MODE", "type": "choice", "choices": ["inherit", "clash_auto", "clash_fixed", "residential"],
         "default": "inherit", "help": "Outlook 出口覆盖；inherit 使用全局模式。"},
        {"key": "CLAUDE_PROXY_MODE", "type": "choice", "choices": ["inherit", "clash_auto", "clash_fixed", "residential"],
         "default": "inherit", "help": "Claude 出口覆盖；可与 Outlook 使用不同出口。"},
        {"key": "CHATGPT_PROXY_MODE", "type": "choice", "choices": ["inherit", "clash_auto", "clash_fixed", "residential"],
         "default": "inherit", "help": "ChatGPT 出口覆盖；可与 Outlook 使用不同出口。"},
        {"key": "GROK_PROXY_MODE", "type": "choice", "choices": ["inherit", "clash_auto", "clash_fixed", "residential"],
         "default": "inherit", "help": "Grok 出口覆盖；可与 Outlook 使用不同出口。"},
        {"key": "KIRO_PROXY_MODE", "type": "choice", "choices": ["inherit", "clash_auto", "clash_fixed", "residential"],
         "default": "inherit", "help": "Kiro 出口覆盖；可与 Outlook 使用不同出口。"},
        {"key": "GITHUB_PROXY_MODE", "type": "choice", "choices": ["inherit", "clash_auto", "clash_fixed", "residential"],
         "default": "inherit", "help": "GitHub 出口覆盖；可与 Outlook 使用不同出口。"},
        {"key": "CLASH_SECRET", "required": True, "secret": True,
         "help": "Clash Verge → 设置 → 外部控制器(External Controller) 里设的 secret/密钥。"
                 "若该处留空,这里也留空。设了密钥不填会连不上控制器(节点切换失效)。"},
        {"key": "CLASH_API", "default": "http://127.0.0.1:9097",
         "help": "Clash 控制器地址。Clash Verge 默认端口 9097,mihomo 内核默认 9090。在 外部控制器 页可看到。"},
        {"key": "CLASH_PROXY", "default": "http://127.0.0.1:7897",
         "help": "Clash 混合代理端口(mixed-port),脚本走它出网。Verge 默认 7897。"},
        {"key": "CLASH_GROUP", "default": "GLOBAL",
         "help": "决定出口的代理组名。global 模式下填 GLOBAL;规则模式填你的节点选择组名。"},
        {"key": "CLASH_FIXED_NODE", "help": "固定节点模式使用的 Clash 节点全名。"},
        {"key": "REG_FACTORY_PROXY", "secret": True,
         "help": "住宅代理 URL，例如 http://user:pass@host:port 或 socks5://..."},
        {"key": "REG_FACTORY_PROXY_POOL", "secret": True,
         "help": "住宅代理池；.env 中使用逗号分隔，专用网络页支持逐行填写。"},
        {"key": "REG_FACTORY_PROXY_ROTATE_URL", "secret": True,
         "help": "可选的住宅代理供应商换 IP 接口。"},
        {"key": "REG_FACTORY_PROXY_ROTATE_METHOD", "type": "choice", "choices": ["GET", "POST"],
         "default": "GET", "help": "调用换 IP 接口时使用的方法。"},
        {"key": "REG_FACTORY_RESIDENTIAL_TRAFFIC_MODE", "type": "choice",
         "choices": ["extreme", "aggressive", "balanced", "off"], "default": "balanced",
         "help": "住宅代理浏览器节流：极限模式还会压制 BitBrowser 后台联网、预取、清单和更多遥测；验证码域名始终放行。"},
        {"key": "OUTLOOK_GRAPH_AUTH_TIMEOUT", "type": "int", "default": 240,
         "help": "Outlook 注册完成后的 Graph 授权独立超时秒数，不计入注册阶段超时。"},
        {"key": "REG_FACTORY_MAX_CONCURRENCY", "type": "int", "default": 10,
         "help": "单个注册任务允许的最大并发数，防止浏览器和代理资源过载。"},
        {"key": "REG_FACTORY_ALLOW_SHARED_EGRESS", "type": "bool", "default": False,
         "help": "允许多个并发账号共享同一公网出口；默认关闭以降低关联和限流风险。"},
        {"key": "CHATGPT_RESIDENTIAL_ROTATE_RETRIES", "default": "3",
         "help": "ChatGPT 遇到 Cloudflare 拦截时最多轮换住宅 IP 的次数。"},
        {"key": "CHATGPT_GOTO_TIMEOUT_SECONDS", "type": "int", "default": 30,
         "help": "ChatGPT 登录页单次导航超时；超时后会检查已提交页面，否则换节点并新建标签页。"},
        {"key": "CHATGPT_GOTO_ATTEMPTS", "type": "int", "default": 3,
         "help": "ChatGPT 登录页最多导航次数，范围 1 到 4。"},
    ]},
    {"group": "指纹浏览器", "tests": [{"target": "bitbrowser", "label": "测试 指纹浏览器连通"}], "items": [
        {"key": "FINGERPRINT_BROWSER", "type": "choice", "choices": ["bitbrowser", "cloak", "roxy", "bundled", "custom", "adspower", "custom_api"],
         "default": "bitbrowser", "help": "默认保持 BitBrowser 兼容；选择 CloakBrowser/RoxyBrowser 即使用参考项目的指纹浏览器方案。"},
        {"key": "CLOAK_HEADLESS", "type": "bool", "default": True, "help": "CloakBrowser 无头运行；关闭后显示浏览器窗口。"},
        {"key": "CLOAK_HUMANIZE", "type": "bool", "default": True, "help": "启用 CloakBrowser 人工节奏和鼠标键盘行为。"},
        {"key": "CLOAK_GEOIP", "type": "bool", "default": True, "help": "按代理出口自动匹配语言、时区和 WebRTC。"},
        {"key": "CLOAK_LOCALE", "help": "CloakBrowser 语言；留空按出口 IP 自动匹配。"},
        {"key": "CLOAK_TIMEZONE", "help": "CloakBrowser 时区；留空按出口 IP 自动匹配。"},
        {"key": "CLOAK_LICENSE_KEY", "secret": True, "advanced": True, "help": "CloakBrowser Pro license；免费版留空。"},
        {"key": "CLOAK_FINGERPRINT_SEED", "advanced": True, "help": "固定 Cloak 指纹 seed；留空每个账号随机。"},
        {"key": "CLOAK_USER_DATA_DIR", "advanced": True, "help": "持久化浏览器目录；留空每个账号使用临时环境。"},
        {"key": "CLOAK_EXTRA_ARGS", "advanced": True, "help": "额外 Chromium 参数，逗号或换行分隔。"},
        {"key": "CLOAK_KEEP_BROWSER_OPEN", "type": "bool", "advanced": True, "help": "调试时保留 CloakBrowser 窗口。"},
        {"key": "ROXY_API_BASE", "default": "http://127.0.0.1:50100", "help": "RoxyBrowser 本地 API 地址。"},
        {"key": "ROXY_API_TOKEN", "secret": True, "help": "RoxyBrowser API token。"},
        {"key": "ROXY_WORKSPACE_ID", "help": "RoxyBrowser 工作区 ID，创建环境必填。"},
        {"key": "ROXY_PROJECT_ID", "advanced": True, "help": "RoxyBrowser 项目 ID。"},
        {"key": "ROXY_PROFILE_ID", "advanced": True, "help": "固定 Roxy Profile ID；一号一环境模式下留空。"},
        {"key": "ROXY_OPEN_HEADLESS", "type": "bool", "default": True, "help": "RoxyBrowser 无头启动。"},
        {"key": "ROXY_ONE_PROFILE_PER_ACCOUNT", "type": "bool", "default": True, "help": "每个账号创建独立 Roxy 环境。"},
        {"key": "ROXY_DELETE_PROFILE_AFTER_RUN", "type": "bool", "default": True, "help": "注册结束自动删除 Roxy 环境。"},
        {"key": "ROXY_CREATE_USE_PROXY_POOL", "type": "bool", "default": True, "help": "创建 Roxy 环境时传入当前代理。"},
        {"key": "ROXY_RANDOM_OS_ON_CREATE", "type": "bool", "default": True, "help": "创建环境时随机 Windows/macOS 指纹。"},
        {"key": "ROXY_RANDOM_OS_CHOICES", "default": "Windows,macOS", "advanced": True, "help": "Roxy 随机系统候选列表。"},
        {"key": "ROXY_DEFAULT_OS", "default": "macOS", "advanced": True, "help": "关闭随机系统时使用的默认系统。"},
        {"key": "ROXY_PROFILE_NAME_PREFIX", "default": "reg", "advanced": True, "help": "Roxy 环境名称前缀。"},
        {"key": "ROXY_KEEP_BROWSER_OPEN", "type": "bool", "advanced": True, "help": "调试时保留 RoxyBrowser 窗口。"},
        {"key": "REG_FACTORY_BROWSER_PATH", "help": "内置 Chromium 可执行文件路径"},
        {"key": "CUSTOM_BROWSER_PATH", "help": "custom 模式的 Chrome/Chromium 可执行文件；留空会尝试自动查找。"},
        {"key": "CUSTOM_BROWSER_API", "help": "custom_api 的 API 根地址，例如 http://127.0.0.1:5000。"},
        {"key": "CUSTOM_BROWSER_API_MODE", "type": "choice", "choices": ["auto", "generic", "bitbrowser"],
         "default": "auto", "help": "auto 保持 BitBrowser 兼容；generic 对接常见 REST API；bitbrowser 强制旧协议。"},
        {"key": "CUSTOM_BROWSER_API_KEY", "secret": True, "help": "可选 API Key；默认以 Authorization: Bearer <key> 发送。"},
        {"key": "CUSTOM_BROWSER_API_AUTH_HEADER", "default": "Authorization", "advanced": True, "help": "鉴权请求头名称，例如 X-API-Key。"},
        {"key": "CUSTOM_BROWSER_API_AUTH_PREFIX", "default": "Bearer ", "advanced": True, "help": "鉴权值前缀；API Key 直传时留空。"},
        {"key": "CUSTOM_BROWSER_API_HEADERS", "secret": True, "advanced": True, "help": "可选额外请求头 JSON，例如 {\"X-Client\":\"reg-factory\"}。"},
        {"key": "CUSTOM_BROWSER_API_TIMEOUT", "type": "int", "default": "60", "advanced": True, "help": "单次自定义浏览器 API 请求超时秒数。"},
        {"key": "CUSTOM_BROWSER_API_VERIFY_TLS", "type": "bool", "default": True, "advanced": True, "help": "HTTPS API 是否校验证书。"},
        {"key": "CUSTOM_BROWSER_API_ID_FIELD", "default": "id", "advanced": True, "help": "generic API 的 profile ID 字段名。路径可使用 {id} 或 {profile_id}。"},
        {"key": "CUSTOM_BROWSER_API_HEALTH_PATH", "default": "/health", "advanced": True, "help": "连通性测试优先请求的健康检查路径。"},
        {"key": "CUSTOM_BROWSER_API_CREATE_PATH", "default": "/browser/update", "advanced": True, "help": "创建 profile 的路径。"},
        {"key": "CUSTOM_BROWSER_API_LIST_PATH", "default": "/browser/list", "advanced": True, "help": "profile 列表路径。"},
        {"key": "CUSTOM_BROWSER_API_OPEN_PATH", "default": "/browser/open", "advanced": True, "help": "启动 profile 并返回 CDP ws/cdp/endpoint 的路径。"},
        {"key": "CUSTOM_BROWSER_API_CLOSE_PATH", "default": "/browser/close", "advanced": True, "help": "关闭 profile 的路径。"},
        {"key": "CUSTOM_BROWSER_API_DELETE_PATH", "default": "/browser/delete", "advanced": True, "help": "删除 profile 的路径。"},
        {"key": "CUSTOM_BROWSER_API_UPDATE_PATH", "default": "/browser/update/partial", "advanced": True, "help": "更新指纹的路径。"},
        {"key": "CUSTOM_BROWSER_API_CREATE_METHOD", "default": "POST", "advanced": True, "help": "创建请求方法，通常为 POST。"},
        {"key": "CUSTOM_BROWSER_API_LIST_METHOD", "default": "POST", "advanced": True, "help": "列表请求方法，兼容模式为 POST，REST 常见为 GET。"},
        {"key": "CUSTOM_BROWSER_API_OPEN_METHOD", "default": "POST", "advanced": True, "help": "启动请求方法。"},
        {"key": "CUSTOM_BROWSER_API_CLOSE_METHOD", "default": "POST", "advanced": True, "help": "关闭请求方法。"},
        {"key": "CUSTOM_BROWSER_API_DELETE_METHOD", "default": "POST", "advanced": True, "help": "删除请求方法；REST API 常用 DELETE。"},
        {"key": "CUSTOM_BROWSER_API_UPDATE_METHOD", "default": "POST", "advanced": True, "help": "更新指纹请求方法。"},
        {"key": "CUSTOM_BROWSER_API_FORWARD_FIELDS", "type": "bool", "default": False, "advanced": True, "help": "generic 模式将额外 profile 字段原样转发。"},
        {"key": "REG_FACTORY_BROWSER_HELPER", "help": "内置 Chromium 启动器路径"},
        {"key": "BITBROWSER_API", "default": "http://127.0.0.1:54345", "help": "比特浏览器本地 API"},
        {"key": "BB_CORE_VERSION", "default": "146",
         "help": "使用 BitBrowser provider 时，Outlook 自注册等流程的首选 Chromium 内核"},
        {"key": "CHATGPT_BROWSER_CORE_VERSION", "default": "146",
         "help": "ChatGPT 并发 Profile 使用的 Chromium 内核"},
        {"key": "OUTLOOK_BROWSER_FALLBACK_CORE_VERSION", "default": "130",
         "help": "Outlook 首选内核安装失败时自动回退的内核；留空禁用"},
        {"key": "GROK_BROWSER_CORE_VERSION", "default": "146",
         "help": "Grok 浏览器使用的 BitBrowser Chromium 内核；旧 130 会触发 xAI 发码 403"},
        {"key": "ADSPOWER_API", "default": "http://127.0.0.1:50325", "help": "AdsPower 本地 API"},
        {"key": "ADSPOWER_API_KEY", "secret": True, "help": "AdsPower API key，未启用鉴权时留空"},
        {"key": "ADSPOWER_GROUP_ID", "default": "0", "help": "AdsPower 新建 profile 的分组 ID"},
    ]},
    {"group": "Claude 注册与验证", "items": [
        {"key": "CLAUDE_CHALLENGE_WAIT_SECONDS", "default": "45",
         "help": "每个 Clash 节点等待 Cloudflare 自动放行的秒数"},
        {"key": "CLAUDE_CHALLENGE_NODE_RETRIES", "default": "3",
         "help": "auto 模式提交邮箱前最多轮换节点次数"},
        {"key": "CLAUDE_RESIDENTIAL_PROFILE_RETRIES", "default": "3",
         "help": "住宅出口在提交邮箱前被拒绝时，新建浏览器会话的总尝试次数"},
        {"key": "CLAUDE_ALLOW_ROTATING_PROXY", "type": "bool", "default": False,
         "help": "跳过 Claude 住宅代理粘性检测；仅用于已确认出口连续性的特殊代理"},
        {"key": "CLAUDE_NODE_PROBE_LIMIT", "default": "6",
         "help": "启动时最多快速探测的候选节点数"},
        {"key": "CLAUDE_NODE_PROBE_TIMEOUT_SECONDS", "default": "8",
         "help": "单个候选节点的快速探测超时秒数"},
        {"key": "CLAUDE_CAPTCHA_MANUAL_TIMEOUT", "default": "0",
         "help": "自动求解失败后等待人工接管秒数；0 表示关闭"},
        {"key": "CLAUDE_HCAPTCHA_SOLVE_RETRIES", "default": "2",
         "help": "YesCaptcha 备用求解器的瞬时失败重试次数"},
        {"key": "CLAUDE_VISION_API_BASE", "required": True,
         "help": "必填：Claude hCaptcha 视觉解码 API 地址；未配置无法自动通过图形验证"},
        {"key": "CLAUDE_VISION_API_KEY", "required": True, "secret": True,
         "help": "必填：Claude hCaptcha 视觉解码 API key"},
        {"key": "CLAUDE_VISION_MODEL", "default": "gemini-3.6-flash",
         "help": "Claude hCaptcha 主视觉模型"},
        {"key": "CLAUDE_BROWSER_CORE_VERSION", "default": "146",
         "help": "Claude 注册和 sessionKey 校验使用的 Chromium 指纹版本"},
        {"key": "CLAUDE_BROWSER_FALLBACK_CORE_VERSION", "default": "130",
         "help": "首选内核安装失败时，本次 Claude 注册自动回退的 BitBrowser 内核；留空禁用"},
    ]},
    {"group": "短信接码", "tests": [{"target": "smsman", "label": "测试 sms-man"}, {"target": "firefox", "label": "测试 firefox.fun"}], "items": [
        {"key": "SMS_API_NAME", "help": "firefox.fun APIName；在 API 对接页面查看，通常为账号名加两位随机数字"},
        {"key": "SMS_TOKEN", "secret": True, "help": "firefox.fun 持久 token；取号时还会使用 OpenAI 项目 ID"},
        {"key": "HERO_SMS_API_KEY", "secret": True, "help": "hero-sms.com 备用接码 key"},
        {"key": "SMSMAN_TOKEN", "secret": True, "help": "sms-man.com 接码 key(Codex add-phone 主用)"},
        {"key": "SMSMAN_APP_ID_OPENAI", "default": "openai", "help": "sms-man OpenAI 服务 id(openai 自动解析为 2754)"},
        {"key": "SMSMAN_APP_ID_GMAIL", "default": "google", "help": "sms-man Gmail/Google 服务 id(google 自动解析;接码助手默认用它)"},
        {"key": "SMSMAN_COUNTRY_ID_OPENAI", "default": "0", "help": "国家 id(0=随机/按价格)"},
        {"key": "CUSTOM_SMS_ALLOWED_HOSTS", "help": "自定义接码记录域名白名单；仅对明确添加的 host 放宽 DNS 公网校验"},
    ]},
    {"group": "打码平台(可选)", "items": [
        {"key": "CAPSOLVER_API_KEY", "secret": True, "help": "CapSolver 打码 key"},
        {"key": "EZCAPTCHA_API_KEY", "secret": True, "help": "EZ-Captcha 打码 key(解锁 Outlook 用)"},
        {"key": "YESCAPTCHA_API_KEY", "secret": True, "help": "YesCaptcha key (Claude hCaptcha / Grok Turnstile / GitHub Arkose)"},
    ]},
    {"group": "Outlook 自注册",
     "notice": "需要提取 Graph RT 时，必须配置可接收验证码的辅助邮箱。请选择 YYDS/custom，或选择 outlook 并填入下方四段凭据；未配置时 Microsoft 安全信息页无法完成授权。",
     "notice_level": "warning",
     "tests": [{"target": "outlook-recovery", "label": "验证 Outlook 辅助邮箱 RT"}],
     "items": [
        {"key": "OUTLOOK_PROXIES", "help": "Outlook 自注册住宅代理池(换行/逗号分隔)"},
        {"key": "OUTLOOK_UI_LOCALE", "default": "en-US",
         "help": "Microsoft 页面语言提示；印度可用 hi-IN，印度尼西亚可用 id-ID"},
        {"key": "OUTLOOK_EMAIL_DOMAIN", "default": "auto",
         "help": "auto 按当前网络出口的注册页域名选项选择；也可填 outlook.jp、outlook.eu 或其它区域后缀"},
        {"key": "OUTLOOK_NODE_REGION_KEYWORDS", "default": "",
         "help": "Outlook Clash 节点国家关键词，逗号分隔；留空沿用 NODE_REGION_KEYWORDS"},
        {"key": "OUTLOOK_NODE_EXCLUDE_REGION_KEYWORDS", "default": "香港,Hong Kong,🇭🇰",
         "help": "Outlook Clash 强制排除的节点国家关键词；默认排除香港"},
        {"key": "OUTLOOK_GRAPH_RECOVERY_EMAIL", "type": "bool",
         "default": "true", "help": "启用 Graph proofs/Add 辅助邮箱自动绑定和接码；关闭后无法保证 RT 可提取"},
        {"key": "OUTLOOK_GRAPH_RECOVERY_PROVIDER", "type": "choice", "choices": ["yyds", "custom", "outlook"],
         "default": "yyds", "help": "Graph 辅助邮箱提供方；outlook 使用下方用户自有邮箱并通过 Graph API 收码"},
        {"key": "OUTLOOK_GRAPH_RECOVERY_OUTLOOK_MAILBOX", "secret": True,
         "help": "provider=outlook 时必填：email@outlook.com----password----refresh_token----client_id。保存前可点本组验证按钮检查 Graph API。"},
        {"key": "OUTLOOK_GRAPH_RECOVERY_TIMEOUT", "default": "120", "help": "Graph 辅助邮箱验证码最大等待秒数"},
        {"key": "OUTLOOK_GRAPH_RECOVERY_POLL_INTERVAL", "default": "5", "help": "Graph 辅助邮箱轮询间隔秒数"},
    ]},
    {"group": "ChatGPT 邮箱", "items": [
        {"key": "CHATGPT_EMAIL_PROVIDER", "type": "choice", "choices": ["pool", "icloud", "remail"],
         "default": "pool", "help": "ChatGPT 默认邮箱来源；icloud/Remail 自动申请并轮询验证码"},
        {"key": "CHATGPT_ENABLE_2FA", "type": "choice", "choices": ["true", "false"],
         "default": "true", "help": "注册完成后重认证并启用验证器 TOTP，同时保存密钥"},
        {"key": "CHATGPT_VERIFICATION_CODE_TIMEOUT", "type": "int", "default": "90",
         "help": "ChatGPT 重发验证码后，邮箱 API 最长等待秒数，建议 60-120"},
        {"key": "CHATGPT_VERIFICATION_POLL_INTERVAL", "type": "int", "default": "5",
         "help": "ChatGPT 邮箱 API 轮询间隔秒数，建议 3-8"},
        {"key": "ICLOUD_MAIL_API_BASE", "default": "https://mail.no-replyca.xyz",
         "help": "iCloud 邮箱 API 请求地址；email.manageh.shop 是文档站，不是接口地址"},
        {"key": "ICLOUD_MAIL_API_KEY", "secret": True, "help": "iCloud 邮箱 API key"},
        {"key": "ICLOUD_MAIL_TYPE", "type": "choice", "choices": ["icloud-code", "icloud"],
         "default": "icloud-code", "help": "ChatGPT 注册固定使用低成本 iCloud 子邮箱；此项供其它流程选择邮箱类型"},
        {"key": "ICLOUD_MAIL_SERVICE", "default": "openai", "help": "ChatGPT 固定按 openai 服务申请接码邮箱"},
    ]},
    {"group": "临时邮箱(Claude/Grok 注册取码)", "tests": [{"target": "yyds", "label": "测试 YYDS"}], "items": [
        {"key": "CLAUDE_USE_TEMP_EMAIL", "type": "choice", "choices": ["false", "true"], "default": "false",
         "help": "Claude 命令行未指定邮箱时默认使用下方临时邮箱；任务表单选择 provider 时无需打开"},
        {"key": "TEMP_EMAIL_PROVIDER", "type": "choice",
         "choices": ["yyds", "gptmail", "moemail", "cfmail", "icloud", "remail", "custom"], "default": "yyds",
         "help": "Claude/Grok 默认临时邮箱 provider(需配好对应 key)，任务表单也可临时指定。"},
        {"key": "YYDS_API_KEY", "secret": True, "help": "YYDS Mail key(profile 页,AC- 开头)"},
        {"key": "YYDS_BASE_URL", "default": "https://maliapi.215.im", "help": "YYDS Mail API 根地址；可粘贴 vip.215.im 或完整 /v1/accounts 地址，程序会自动纠正"},
        {"key": "GPTMAIL_API_KEY", "secret": True, "help": "GPTMail key(mail.chatgpt.org.uk)"},
        {"key": "MOEMAIL_API_KEY", "secret": True, "help": "MoeMail key(自部署)"},
        {"key": "MOEMAIL_BASE_URL", "help": "MoeMail 自部署地址"},
        {"key": "CFMAIL_ADMIN_PASSWORD", "secret": True, "help": "Cloudflare Temp Email admin 密码(自部署)"},
        {"key": "CFMAIL_BASE_URL", "help": "Cloudflare Temp Email 地址"},
        {"key": "REMAIL_BASE_URL", "default": "https://remail.aishop6.com", "help": "Remail API 地址"},
        {"key": "REMAIL_API_KEY", "secret": True, "help": "Remail Bearer API key（rk- 开头）"},
        {"key": "REMAIL_PROJECT_ID", "type": "int", "default": "0", "help": "Remail 项目 ID；选择 Kiro 项目通常为 58"},
        {"key": "REMAIL_EMAIL_SUFFIX", "default": "outlook.com", "help": "Remail 邮箱后缀"},
        {"key": "REMAIL_SUPPLY", "default": "private_first", "help": "Remail 供应策略；通常保持 private_first"},
    ]},
    {"group": "SUB2API(Codex / Grok 导入)", "items": [
        {"key": "SUB2API_URL", "help": "SUB2API 管理接口地址"},
        {"key": "SUB2API_EMAIL", "help": "SUB2API 登录邮箱"},
        {"key": "SUB2API_PASSWORD", "secret": True, "help": "SUB2API 登录密码"},
        {"key": "SUB2API_GROUP", "default": "codex", "help": "Codex 目标分组名(platform=openai)"},
        {"key": "SUB2API_GROK_GROUP", "default": "grok", "help": "Grok 目标分组名(platform=grok，需后台先建好)"},
        {"key": "SUB2API_GROK_PROXY_ID", "type": "int", "default": 0,
         "help": "可选：SUB2API 后台代理 ID，供 Grok SSO 转 OAuth 使用；0=不指定"},
    ]},
    {"group": "CPA(codex 授权文件导入)", "items": [
        {"key": "CPA_URL", "help": "CPA 管理接口地址"},
        {"key": "CPA_MGMT_KEY", "secret": True, "help": "CPA 管理 key"},
        {"key": "CODEX_AUTH_URL_SOURCE", "type": "choice", "choices": ["sub2", "cpa"],
         "default": "sub2", "help": "Codex 授权地址来源；cpa 模式由 CPA 生成 PKCE 并直接接收 callback。"},
        {"key": "CODEX_CPA_CALLBACK_RETRIES", "type": "int", "default": 5,
         "help": "CPA callback 遇到 409/429/5xx 时的重试次数。"},
        {"key": "CODEX_CPA_CALLBACK_RETRY_DELAY", "type": "int", "default": 3,
         "help": "CPA callback 重试基础间隔秒数。"},
    ]},
    {"group": "chatgpt2api(普通网页号)", "items": [
        {"key": "CHATGPT2API_URL", "help": "chatgpt2api host(用 --import-c2a 时必填)"},
        {"key": "CHATGPT2API_KEY", "secret": True, "help": "chatgpt2api admin key"},
    ]},
    {"group": "webchat2api(Grok sso)", "items": [
        {"key": "WEBCHAT2API_URL", "help": "webchat2api 地址(用 Grok 时)"},
        {"key": "WEBCHAT2API_KEY", "secret": True, "help": "webchat2api key"},
    ]},
    {"group": "Codex add-phone 接码调参", "items": [
        {"key": "CODEX_PHONE_SKIP_ATTEMPTS", "default": "0", "help": "先赌免手机次数(0=直接接码)"},
        {"key": "CODEX_ADDPHONE_ATTEMPTS", "default": "2", "help": "接码换号上限次数"},
        {"key": "CODEX_SMS_TIMEOUT", "default": "150", "help": "单号等码超时(秒)"},
        {"key": "SMS_COUNTRY_BLACKLIST_OPENAI", "default": "261,63", "help": "拉黑号段(dialing code)"},
    ]},
    {"group": "视觉模型与投票(可选)", "items": [
        {"key": "VISION_API_BASE", "help": "Claude/GitHub 共用的主视觉网关(OpenAI 兼容)"},
        {"key": "VISION_API_KEY", "secret": True, "help": "主视觉网关 key"},
        {"key": "VOTE_ZZ_BASE", "help": "投票中转网关(gemini/gpt)"},
        {"key": "VOTE_ZZ_KEY", "secret": True, "help": "投票网关 gemini key"},
        {"key": "VOTE_GPT_KEY", "secret": True, "help": "投票网关 gpt key"},
        {"key": "VOTE_OPUS_BASE", "help": "claude opus 专用网关"},
        {"key": "VOTE_OPUS_KEY", "secret": True, "help": "opus 网关 key"},
    ]},
]


# Smart view keeps normal setup compact. Values outside this set remain
# available through each group's "show all" control, and any value the user
# has already customized is surfaced automatically by the frontend.
_SMART_ENV_KEYS = {
    "REG_FACTORY_ASSET_API_KEY",
    "REG_FACTORY_PROTOCOL_PAYMENT_ROOT",
    "PROXY_MODE", "CLASH_SECRET", "CLASH_API", "CLASH_PROXY", "CLASH_GROUP",
    "CLASH_FIXED_NODE", "REG_FACTORY_PROXY", "REG_FACTORY_PROXY_POOL",
    "FINGERPRINT_BROWSER", "CLOAK_HEADLESS", "CLOAK_HUMANIZE", "CLOAK_GEOIP",
    "CLOAK_LOCALE", "CLOAK_TIMEZONE", "CLOAK_LICENSE_KEY", "CLOAK_FINGERPRINT_SEED",
    "ROXY_API_BASE", "ROXY_API_TOKEN", "ROXY_WORKSPACE_ID", "ROXY_PROJECT_ID",
    "ROXY_OPEN_HEADLESS", "ROXY_ONE_PROFILE_PER_ACCOUNT", "ROXY_DELETE_PROFILE_AFTER_RUN",
    "CUSTOM_BROWSER_PATH", "CUSTOM_BROWSER_API",
    "CUSTOM_BROWSER_API_MODE", "CUSTOM_BROWSER_API_KEY", "BITBROWSER_API",
    "ADSPOWER_API", "ADSPOWER_API_KEY", "ADSPOWER_GROUP_ID",
    "CLAUDE_VISION_API_BASE", "CLAUDE_VISION_API_KEY",
    "SMS_API_NAME", "SMS_TOKEN", "HERO_SMS_API_KEY", "SMSMAN_TOKEN",
    "CAPSOLVER_API_KEY", "EZCAPTCHA_API_KEY", "YESCAPTCHA_API_KEY",
    "OUTLOOK_GRAPH_RECOVERY_EMAIL", "OUTLOOK_GRAPH_RECOVERY_PROVIDER",
    "OUTLOOK_GRAPH_RECOVERY_OUTLOOK_MAILBOX",
    "CHATGPT_EMAIL_PROVIDER", "CHATGPT_ENABLE_2FA", "ICLOUD_MAIL_API_BASE",
    "ICLOUD_MAIL_API_KEY", "ICLOUD_MAIL_TYPE", "ICLOUD_MAIL_SERVICE",
    "CLAUDE_USE_TEMP_EMAIL", "TEMP_EMAIL_PROVIDER",
    "YYDS_API_KEY", "YYDS_BASE_URL", "GPTMAIL_API_KEY", "MOEMAIL_API_KEY",
    "MOEMAIL_BASE_URL", "CFMAIL_ADMIN_PASSWORD", "CFMAIL_BASE_URL",
    "REMAIL_BASE_URL", "REMAIL_API_KEY", "REMAIL_PROJECT_ID",
    "REMAIL_EMAIL_SUFFIX", "REMAIL_SUPPLY",
    "SUB2API_URL", "SUB2API_EMAIL", "SUB2API_PASSWORD", "SUB2API_GROUP",
    "CODEX_AUTH_URL_SOURCE", "CPA_URL", "CPA_MGMT_KEY",
    "CHATGPT2API_URL", "CHATGPT2API_KEY", "WEBCHAT2API_URL", "WEBCHAT2API_KEY",
    "VISION_API_BASE", "VISION_API_KEY", "VOTE_ZZ_BASE", "VOTE_ZZ_KEY",
    "VOTE_GPT_KEY", "VOTE_OPUS_BASE", "VOTE_OPUS_KEY",
}

_ENV_LABELS = {
    # Codex K12 / local assets
    "K12_CONSOLE_URL": "K12 控制台地址",
    "K12_AUTO_START": "自动启动 K12 控制台",
    "REG_FACTORY_ASSET_API_KEY": "本地资产 API 密钥",
    "ASSET_SCAN_CHATGPT_PLUS_TRIAL": "扫描 Plus 免费试用资格",
    "ASSET_SCAN_CHATGPT_PLUS_CAMPAIGN": "Plus 试用活动标识",
    "REG_FACTORY_PROTOCOL_PAYMENT_ROOT": "Plus 协议提链程序目录",
    # Network
    "PROXY_MODE": "默认代理模式",
    "OUTLOOK_PROXY_MODE": "Outlook 代理模式",
    "CLAUDE_PROXY_MODE": "Claude 代理模式",
    "CHATGPT_PROXY_MODE": "ChatGPT 代理模式",
    "GROK_PROXY_MODE": "Grok 代理模式",
    "KIRO_PROXY_MODE": "Kiro 代理模式",
    "GITHUB_PROXY_MODE": "GitHub 代理模式",
    "CLASH_SECRET": "Clash 控制器密钥",
    "CLASH_API": "Clash 控制器地址",
    "CLASH_PROXY": "Clash 本地代理地址",
    "CLASH_GROUP": "Clash 节点组名称",
    "CLASH_FIXED_NODE": "Clash 固定节点",
    "REG_FACTORY_PROXY": "住宅代理地址",
    "REG_FACTORY_PROXY_POOL": "住宅代理池",
    "REG_FACTORY_PROXY_ROTATE_URL": "住宅代理换 IP 地址",
    "REG_FACTORY_PROXY_ROTATE_METHOD": "住宅代理换 IP 方法",
    "REG_FACTORY_RESIDENTIAL_TRAFFIC_MODE": "住宅代理流量模式",
    "OUTLOOK_GRAPH_AUTH_TIMEOUT": "Outlook Graph 授权超时",
    "REG_FACTORY_MAX_CONCURRENCY": "最大并发数",
    "REG_FACTORY_ALLOW_SHARED_EGRESS": "允许并发共用出口",
    "CHATGPT_RESIDENTIAL_ROTATE_RETRIES": "ChatGPT 住宅代理轮换次数",
    "CHATGPT_GOTO_TIMEOUT_SECONDS": "ChatGPT 页面打开超时",
    "CHATGPT_GOTO_ATTEMPTS": "ChatGPT 页面打开次数",
    # Fingerprint browsers
    "FINGERPRINT_BROWSER": "指纹浏览器类型",
    "CLOAK_HEADLESS": "CloakBrowser 无头运行",
    "CLOAK_HUMANIZE": "CloakBrowser 人工行为",
    "CLOAK_GEOIP": "CloakBrowser 出口地理匹配",
    "CLOAK_LOCALE": "CloakBrowser 语言",
    "CLOAK_TIMEZONE": "CloakBrowser 时区",
    "CLOAK_LICENSE_KEY": "CloakBrowser license 密钥",
    "CLOAK_FINGERPRINT_SEED": "CloakBrowser 指纹 seed",
    "CLOAK_USER_DATA_DIR": "CloakBrowser 持久化目录",
    "CLOAK_EXTRA_ARGS": "CloakBrowser 额外参数",
    "CLOAK_KEEP_BROWSER_OPEN": "保留 CloakBrowser 窗口",
    "ROXY_API_BASE": "RoxyBrowser API 地址",
    "ROXY_API_TOKEN": "RoxyBrowser API token 密钥",
    "ROXY_WORKSPACE_ID": "RoxyBrowser 工作区 ID",
    "ROXY_PROJECT_ID": "RoxyBrowser 项目 ID",
    "ROXY_PROFILE_ID": "RoxyBrowser Profile ID 环境",
    "ROXY_OPEN_HEADLESS": "RoxyBrowser 无头启动",
    "ROXY_ONE_PROFILE_PER_ACCOUNT": "Roxy 一号一环境",
    "ROXY_DELETE_PROFILE_AFTER_RUN": "注册后删除 Roxy 环境",
    "ROXY_CREATE_USE_PROXY_POOL": "Roxy 使用当前代理",
    "ROXY_RANDOM_OS_ON_CREATE": "Roxy 随机系统指纹",
    "ROXY_RANDOM_OS_CHOICES": "Roxy 系统候选列表",
    "ROXY_DEFAULT_OS": "Roxy 默认系统",
    "ROXY_PROFILE_NAME_PREFIX": "Roxy 环境名称前缀",
    "ROXY_KEEP_BROWSER_OPEN": "保留 RoxyBrowser 窗口",
    "REG_FACTORY_BROWSER_PATH": "内置 Chromium 路径",
    "CUSTOM_BROWSER_PATH": "自定义 Chrome 路径",
    "CUSTOM_BROWSER_API": "自定义浏览器 API 地址",
    "CUSTOM_BROWSER_API_MODE": "自定义浏览器 API 模式",
    "CUSTOM_BROWSER_API_KEY": "自定义浏览器 API 密钥",
    "CUSTOM_BROWSER_API_AUTH_HEADER": "鉴权请求头名称",
    "CUSTOM_BROWSER_API_AUTH_PREFIX": "鉴权值前缀",
    "CUSTOM_BROWSER_API_HEADERS": "额外请求头",
    "CUSTOM_BROWSER_API_TIMEOUT": "API 请求超时",
    "CUSTOM_BROWSER_API_VERIFY_TLS": "校验 HTTPS 证书",
    "CUSTOM_BROWSER_API_ID_FIELD": "Profile ID 字段名",
    "CUSTOM_BROWSER_API_HEALTH_PATH": "健康检查路径",
    "CUSTOM_BROWSER_API_CREATE_PATH": "创建 Profile 路径",
    "CUSTOM_BROWSER_API_LIST_PATH": "Profile 列表路径",
    "CUSTOM_BROWSER_API_OPEN_PATH": "启动 Profile 路径",
    "CUSTOM_BROWSER_API_CLOSE_PATH": "关闭 Profile 路径",
    "CUSTOM_BROWSER_API_DELETE_PATH": "删除 Profile 路径",
    "CUSTOM_BROWSER_API_UPDATE_PATH": "更新指纹路径",
    "CUSTOM_BROWSER_API_CREATE_METHOD": "创建请求方法",
    "CUSTOM_BROWSER_API_LIST_METHOD": "列表请求方法",
    "CUSTOM_BROWSER_API_OPEN_METHOD": "启动请求方法",
    "CUSTOM_BROWSER_API_CLOSE_METHOD": "关闭请求方法",
    "CUSTOM_BROWSER_API_DELETE_METHOD": "删除请求方法",
    "CUSTOM_BROWSER_API_UPDATE_METHOD": "更新指纹请求方法",
    "CUSTOM_BROWSER_API_FORWARD_FIELDS": "转发额外 Profile 字段",
    "REG_FACTORY_BROWSER_HELPER": "内置浏览器启动器路径",
    "BITBROWSER_API": "BitBrowser API 地址",
    "BB_CORE_VERSION": "BitBrowser 默认内核版本",
    "CHATGPT_BROWSER_CORE_VERSION": "ChatGPT 浏览器内核版本",
    "OUTLOOK_BROWSER_FALLBACK_CORE_VERSION": "Outlook 备用内核版本",
    "GROK_BROWSER_CORE_VERSION": "Grok 浏览器内核版本",
    "ADSPOWER_API": "AdsPower API 地址",
    "ADSPOWER_API_KEY": "AdsPower API 密钥",
    "ADSPOWER_GROUP_ID": "AdsPower 分组 ID",
    # Claude
    "CLAUDE_CHALLENGE_WAIT_SECONDS": "Claude 风控等待时间",
    "CLAUDE_CHALLENGE_NODE_RETRIES": "Claude 风控换节点次数",
    "CLAUDE_RESIDENTIAL_PROFILE_RETRIES": "Claude 住宅代理重建次数",
    "CLAUDE_ALLOW_ROTATING_PROXY": "允许 Claude 使用动态代理",
    "CLAUDE_NODE_PROBE_LIMIT": "Claude 候选节点探测数",
    "CLAUDE_NODE_PROBE_TIMEOUT_SECONDS": "Claude 节点探测超时",
    "CLAUDE_CAPTCHA_MANUAL_TIMEOUT": "Claude 人工验证码等待时间",
    "CLAUDE_HCAPTCHA_SOLVE_RETRIES": "Claude hCaptcha 重试次数",
    "CLAUDE_VISION_API_BASE": "Claude 视觉识别 API 地址",
    "CLAUDE_VISION_API_KEY": "Claude 视觉识别 API 密钥",
    "CLAUDE_VISION_MODEL": "Claude 视觉识别模型",
    "CLAUDE_BROWSER_CORE_VERSION": "Claude 浏览器内核版本",
    "CLAUDE_BROWSER_FALLBACK_CORE_VERSION": "Claude 备用内核版本",
    # SMS and captcha
    "SMS_API_NAME": "firefox.fun API 账号名",
    "SMS_TOKEN": "firefox.fun 接码令牌",
    "HERO_SMS_API_KEY": "Hero SMS API 密钥",
    "SMSMAN_TOKEN": "SMS-Man 接码令牌",
    "SMSMAN_APP_ID_OPENAI": "SMS-Man OpenAI 项目",
    "SMSMAN_APP_ID_GMAIL": "SMS-Man Google 项目",
    "SMSMAN_COUNTRY_ID_OPENAI": "SMS-Man OpenAI 国家",
    "CUSTOM_SMS_ALLOWED_HOSTS": "自定义接码域名白名单",
    "CAPSOLVER_API_KEY": "CapSolver API 密钥",
    "EZCAPTCHA_API_KEY": "EZCaptcha API 密钥",
    "YESCAPTCHA_API_KEY": "YesCaptcha API 密钥",
    # Outlook
    "OUTLOOK_PROXIES": "Outlook 代理列表",
    "OUTLOOK_UI_LOCALE": "Outlook 页面语言",
    "OUTLOOK_EMAIL_DOMAIN": "Outlook 注册邮箱域名",
    "OUTLOOK_NODE_REGION_KEYWORDS": "Outlook 节点地区关键词",
    "OUTLOOK_NODE_EXCLUDE_REGION_KEYWORDS": "Outlook 排除地区关键词",
    "OUTLOOK_GRAPH_RECOVERY_EMAIL": "启用 Outlook 辅助邮箱",
    "OUTLOOK_GRAPH_RECOVERY_PROVIDER": "Outlook 辅助邮箱来源",
    "OUTLOOK_GRAPH_RECOVERY_OUTLOOK_MAILBOX": "自有 Outlook 辅助邮箱",
    "OUTLOOK_GRAPH_RECOVERY_TIMEOUT": "辅助邮箱收码超时",
    "OUTLOOK_GRAPH_RECOVERY_POLL_INTERVAL": "辅助邮箱轮询间隔",
    # ChatGPT and temporary mail
    "CHATGPT_VERIFICATION_CODE_TIMEOUT": "ChatGPT 验证码邮箱等待时间",
    "CHATGPT_VERIFICATION_POLL_INTERVAL": "ChatGPT 验证码轮询间隔",
    "CHATGPT_EMAIL_PROVIDER": "ChatGPT 邮箱来源",
    "CHATGPT_ENABLE_2FA": "注册后开启 ChatGPT 2FA",
    "ICLOUD_MAIL_API_BASE": "iCloud 邮箱 API 地址",
    "ICLOUD_MAIL_API_KEY": "iCloud 邮箱 API 密钥",
    "ICLOUD_MAIL_TYPE": "iCloud 邮箱类型",
    "ICLOUD_MAIL_SERVICE": "iCloud 接码服务",
    "CLAUDE_USE_TEMP_EMAIL": "Claude 使用临时邮箱",
    "TEMP_EMAIL_PROVIDER": "临时邮箱服务商",
    "YYDS_API_KEY": "YYDS 邮箱 API 密钥",
    "YYDS_BASE_URL": "YYDS 邮箱 API 地址",
    "GPTMAIL_API_KEY": "GPTMail API 密钥",
    "MOEMAIL_API_KEY": "MoeMail API 密钥",
    "MOEMAIL_BASE_URL": "MoeMail API 地址",
    "CFMAIL_ADMIN_PASSWORD": "CFMail 管理密码",
    "CFMAIL_BASE_URL": "CFMail API 地址",
    "REMAIL_BASE_URL": "Remail API 地址",
    "REMAIL_API_KEY": "Remail API 密钥",
    "REMAIL_PROJECT_ID": "Remail 项目 ID",
    "REMAIL_EMAIL_SUFFIX": "Remail 邮箱后缀",
    "REMAIL_SUPPLY": "Remail 供应策略",
    # Import services
    "SUB2API_URL": "SUB2API 地址",
    "SUB2API_EMAIL": "SUB2API 管理员邮箱",
    "SUB2API_PASSWORD": "SUB2API 管理员密码",
    "SUB2API_GROUP": "SUB2API Codex 分组",
    "SUB2API_GROK_GROUP": "SUB2API Grok 分组",
    "SUB2API_GROK_PROXY_ID": "SUB2API Grok 代理 ID",
    "CPA_URL": "CPA 管理接口地址",
    "CPA_MGMT_KEY": "CPA 管理密钥",
    "CODEX_AUTH_URL_SOURCE": "Codex 授权地址来源",
    "CODEX_CPA_CALLBACK_RETRIES": "CPA 回调重试次数",
    "CODEX_CPA_CALLBACK_RETRY_DELAY": "CPA 回调重试间隔",
    "CHATGPT2API_URL": "chatgpt2api 地址",
    "CHATGPT2API_KEY": "chatgpt2api 管理密钥",
    "WEBCHAT2API_URL": "webchat2api 地址",
    "WEBCHAT2API_KEY": "webchat2api 管理密钥",
    # Codex phone and vision
    "CODEX_PHONE_SKIP_ATTEMPTS": "Codex 免手机尝试次数",
    "CODEX_ADDPHONE_ATTEMPTS": "Codex 接码换号次数",
    "CODEX_SMS_TIMEOUT": "Codex 单号收码超时",
    "SMS_COUNTRY_BLACKLIST_OPENAI": "OpenAI 接码国家黑名单",
    "VISION_API_BASE": "主视觉模型 API 地址",
    "VISION_API_KEY": "主视觉模型 API 密钥",
    "VOTE_ZZ_BASE": "投票模型中转地址",
    "VOTE_ZZ_KEY": "Gemini 投票模型密钥",
    "VOTE_GPT_KEY": "GPT 投票模型密钥",
    "VOTE_OPUS_BASE": "Opus 模型 API 地址",
    "VOTE_OPUS_KEY": "Opus 模型 API 密钥",
}

for _group in ENV_SCHEMA:
    for _item in _group["items"]:
        _item["label"] = _ENV_LABELS[_item["key"]]
        if _item["key"] in _SMART_ENV_KEYS:
            _item["smart"] = True


# 所有 schema 里出现的 .env key（用于读 .env 时补齐未在模板里的项不丢）
def env_keys():
    keys = []
    for g in ENV_SCHEMA:
        for it in g["items"]:
            keys.append(it["key"])
    return keys
